-- MySQL Script generated by MySQL Workbench
-- mié 07 oct 2020 15:23:13 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amazonasbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amazonasbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amazonasbd` DEFAULT CHARACTER SET utf8 ;
USE `amazonasbd` ;

-- -----------------------------------------------------
-- Table `amazonasbd`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazonasbd`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`Autor` (
  `idAutor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazonasbd`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `paginas` INT NOT NULL,
  `precio` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idLibro`, `Autor_idAutor`),
  INDEX `fk_Libro_Autor_idx` (`Autor_idAutor` ASC),
  CONSTRAINT `fk_Libro_Autor`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `amazonasbd`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazonasbd`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`Carrito` (
  `idCarrito` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCarrito`, `Cliente_idCliente`),
  INDEX `fk_Carrito_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Carrito_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `amazonasbd`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazonasbd`.`Carrito_Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`Carrito_Libro` (
  `idCarrito_Libro` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  PRIMARY KEY (`idCarrito_Libro`, `Carrito_idCarrito`, `Libro_idLibro`),
  INDEX `fk_Carrito_Libro_Carrito1_idx` (`Carrito_idCarrito` ASC),
  INDEX `fk_Carrito_Libro_Libro1_idx` (`Libro_idLibro` ASC),
  CONSTRAINT `fk_Carrito_Libro_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `amazonasbd`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_Libro_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `amazonasbd`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazonasbd`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazonasbd`.`LogAdministrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazonasbd`.`LogAdministrador` (
  `idLogAdministrador` INT NOT NULL,
  `accion` VARCHAR(45) NOT NULL,
  `datos` TEXT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idLogAdministrador`, `Administrador_idAdministrador`),
  INDEX `fk_LogAdministrador_Administrador1_idx` (`Administrador_idAdministrador` ASC),
  CONSTRAINT `fk_LogAdministrador_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `amazonasbd`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
